-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2023-04-08 21:53:41.681

-- tables
-- Table: ALUMNO
CREATE TABLE ALUMNO (
    CODALU char(3)  NOT NULL,
    NOMALU varchar(50)  NOT NULL,
    APEALU varchar(50)  NOT NULL,
    CELALU char(9)  NOT NULL,
    GMAALU varchar(100)  NULL,
    DNIALU char(8)  NOT NULL,
    FECNACALU date  NOT NULL,
    GRAALU char(1)  NOT NULL,
    SECALU char(1)  NOT NULL,
    TURALU char(1)  NOT NULL,
    CICALU char(3)  NOT NULL,
    CONSTRAINT ALUMNO_pk PRIMARY KEY  (CODALU)
);

-- Table: ASISTENCIA
CREATE TABLE ASISTENCIA (
    CODREG char(4)  NOT NULL,
    ESTASI char(1)  NOT NULL,
    FECASI date  NOT NULL,
    PROFESOR_CODPRO char(3)  NOT NULL,
    ALUMNO_CODALU char(3)  NOT NULL,
    CONSTRAINT ASISTENCIA_pk PRIMARY KEY  (CODREG)
);

-- Table: LOGIN
CREATE TABLE LOGIN (
    CODLOG char(3)  NOT NULL,
    CLALOG varchar(20)  NOT NULL,
    USULOG varchar(100)  NOT NULL,
    USUARIO_CODPRO char(3)  NOT NULL,
    CONSTRAINT LOGIN_pk PRIMARY KEY  (CODLOG)
);

-- Table: MATERIA
CREATE TABLE MATERIA (
    CODMAT int  NOT NULL,
    NOMMAT varchar(50)  NOT NULL,
    USUARIO_CODUSU char(3)  NOT NULL,
    CONSTRAINT MATERIA_pk PRIMARY KEY  (CODMAT)
);

-- Table: USUARIO
CREATE TABLE USUARIO (
    CODUSU char(3)  NOT NULL,
    NOMUSU varchar(50)  NOT NULL,
    APEUSU varchar(50)  NOT NULL,
    CELUSU char(9)  NOT NULL,
    DNIUSU varchar(8)  NOT NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY  (CODUSU)
);

-- foreign keys
-- Reference: ALUMNO_REGISTRO (table: ASISTENCIA)
ALTER TABLE ASISTENCIA ADD CONSTRAINT ALUMNO_REGISTRO
    FOREIGN KEY (ALUMNO_CODALU)
    REFERENCES ALUMNO (CODALU);

-- Reference: LOGIN_USUARIO (table: LOGIN)
ALTER TABLE LOGIN ADD CONSTRAINT LOGIN_USUARIO
    FOREIGN KEY (USUARIO_CODPRO)
    REFERENCES USUARIO (CODUSU);

-- Reference: MATERIA_USUARIO (table: MATERIA)
ALTER TABLE MATERIA ADD CONSTRAINT MATERIA_USUARIO
    FOREIGN KEY (USUARIO_CODUSU)
    REFERENCES USUARIO (CODUSU);

-- Reference: PROFESOR_REGISTRO (table: ASISTENCIA)
ALTER TABLE ASISTENCIA ADD CONSTRAINT PROFESOR_REGISTRO
    FOREIGN KEY (PROFESOR_CODPRO)
    REFERENCES USUARIO (CODUSU);

-- End of file.

